-- Source: wf_DI_ITEM_MTRL_MASTER.XML
-- Staging model for material source data
-- Converted from Informatica source definition

{{ config(
    materialized='view',
    tags=['staging', 'material_master']
) }}

select
    -- Core material fields
    cast(product as varchar(40)) as product,
    cast(matergrppckgmater as varchar(4)) as matergrppckgmater,
    cast(productgroup as varchar(9)) as productgroup,
    cast(weightunit as varchar(3)) as weightunit,
    cast(volumeunit as varchar(3)) as volumeunit,
    cast(materialvolume as decimal(13,3)) as materialvolume,
    cast(sizeordimensiontext as varchar(32)) as sizeordimensiontext,
    cast(producthierarchy as varchar(18)) as producthierarchy,
    cast(productoldid as varchar(40)) as productoldid,
    cast(netweight as decimal(13,3)) as netweight,
    cast(labdsgnoffc as varchar(3)) as labdsgnoffc,
    cast(productstandardid as varchar(18)) as productstandardid,
    cast(grossweight as decimal(13,3)) as grossweight,
    cast(itemcategorygroup as varchar(4)) as itemcategorygroup,
    cast(externalproductgroup as varchar(18)) as externalproductgroup,
    cast(division as varchar(2)) as division,
    cast(crossplantstatusvaliditydate as timestamp) as crossplantstatusvaliditydate,
    cast(crossplantstatus as varchar(2)) as crossplantstatus,
    cast(internationalarticlenumbercat as varchar(2)) as internationalarticlenumbercat,
    cast(authorizationgroup as varchar(4)) as authorizationgroup,
    cast(producttype as varchar(4)) as producttype,
    cast(industrysector as varchar(1)) as industrysector,
    
    -- Document management fields
    cast(pgenumdocwithodocmanasys as varchar(3)) as pgenumdocwithodocmanasys,
    cast(industrystandardname as varchar(18)) as industrystandardname,
    cast(docverwithodocmanasys as varchar(2)) as docverwithodocmanasys,
    cast(doctypwithodocmanasys as varchar(3)) as doctypwithodocmanasys,
    cast(docchngenumwithodocumanasys as varchar(6)) as docchngenumwithodocumanasys,
    cast(cadindicator as varchar(1)) as cadindicator,
    cast(basicmaterial as varchar(48)) as basicmaterial,
    cast(pgeformatproducmemo as varchar(4)) as pgeformatproducmemo,
    
    -- Material properties
    cast(indiinbulkliquid as varchar(1)) as indiinbulkliquid,
    cast(indihighlyviscous as varchar(1)) as indihighlyviscous,
    cast(envrmtrelevant as varchar(1)) as envrmtrelevant,
    cast(docnumwithodocmanagsys as varchar(22)) as docnumwithodocmanagsys,
    cast(packcode as varchar(10)) as packcode,
    cast(approvedbatchrecreq as varchar(1)) as approvedbatchrecreq,
    cast(ttlshelflife as decimal(4,0)) as ttlshelflife,
    cast(temppcondindi as varchar(2)) as temppcondindi,
    cast(strgperc as decimal(3,0)) as strgperc,
    cast(strcond as varchar(2)) as strcond,
    cast(roundrlcalsled as varchar(1)) as roundrlcalsled,
    cast(hazardmatnum as varchar(40)) as hazardmatnum,
    cast(contnrreq as varchar(2)) as contnrreq,
    cast(prdindiexpdt as varchar(1)) as prdindiexpdt,
    cast(quantgrgiprnt as decimal(13,3)) as quantgrgiprnt,
    cast(minremshelf as decimal(4,0)) as minremshelf,
    cast(labeltype as varchar(2)) as labeltype,
    cast(labelform as varchar(2)) as labelform,
    cast(serialnoexplicitneslevel as varchar(1)) as serialnoexplicitneslevel,
    cast(manufacturernumber as varchar(10)) as manufacturernumber,
    cast(varblpurordunitisactive as varchar(1)) as varblpurordunitisactive,
    cast(purchngvalkey as varchar(4)) as purchngvalkey,
    cast(materqualdisckind as varchar(1)) as materqualdisckind,
    cast(purchaseorderquantityunit as varchar(3)) as purchaseorderquantityunit,
    cast(manufacturerpartprofile as varchar(4)) as manufacturerpartprofile,
    cast(productmanufacturernumber as varchar(40)) as productmanufacturernumber,
    cast(materialfrieghtgroup as varchar(8)) as materialfrieghtgroup,
    
    -- Audit fields
    cast(createdbyuser as varchar(12)) as createdbyuser,
    cast(creationdate as timestamp) as creationdate,
    cast(lastchangedbyuser as varchar(12)) as lastchangedbyuser,
    cast(lastchangedate as timestamp) as lastchangedate,
    cast(baseunit1 as varchar(3)) as baseunit1,
    cast(danger_goods_ind as varchar(3)) as danger_goods_ind,
    cast(isbatchmanagementrequired1 as varchar(1)) as isbatchmanagementrequired1,
    cast(disposable_ind1 as varchar(1)) as disposable_ind1,
    cast(expiry_ind1 as varchar(1)) as expiry_ind1,
    cast(sterile_ind1 as varchar(1)) as sterile_ind1,
    cast(serialized_ind1 as varchar(1)) as serialized_ind1,
    cast(maintst1 as varchar(15)) as maintst1,
    cast(commodity1 as varchar(18)) as commodity1,
    cast(countryoforiginmaterial1 as varchar(3)) as countryoforiginmaterial1,
    cast(productdescription1 as varchar(40)) as productdescription1,
    
    -- Extended attributes (will be populated by lookups)
    cast(null as varchar(70)) as pvc_free_ind,
    cast(null as varchar(70)) as dehp_free_ind,
    cast(null as varchar(70)) as mercury_free_ind,
    cast(null as varchar(70)) as latex_ind,
    cast(null as varchar(70)) as hazardous_ind,
    cast(null as varchar(70)) as eccn_nbr,
    cast(null as varchar(70)) as pto_relevant,
    cast(null as varchar(70)) as pto_relevant_qnty,
    cast(null as varchar(70)) as ce_mark_ind,
    cast(null as varchar(70)) as fda_prod_cd,
    cast(null as varchar(70)) as dps_generic_lot,
    cast(null as varchar(70)) as dps_uom_qty,
    cast(null as varchar(70)) as rebox_id,
    cast(null as varchar(70)) as rework_ind,
    cast(null as varchar(70)) as hyp_cd,
    cast(null as varchar(70)) as hyp_brand_desc,
    cast(null as varchar(70)) as mtrl_thk_ind,
    cast(null as decimal(6,2)) as mtrl_thk_upr_limit,
    cast(null as decimal(6,2)) as mtrl_thk_lwr_limit,
    cast(null as varchar(70)) as mtrl_thk_msrmt,
    cast(pckgmatertyp as varchar(4)) as pckgmatertyp,
    cast(handlingunittype as varchar(4)) as handlingunittype,
    cast(unitspecificproductlength as decimal(13,3)) as unitspecificproductlength,
    cast(unitspecificproductwidth as decimal(13,3)) as unitspecificproductwidth,
    cast(unitspecificproductheight as decimal(13,3)) as unitspecificproductheight,
    cast(productmeasurementunit as varchar(3)) as productmeasurementunit,
    cast(null as varchar(70)) as shpng_rstrctn,
    cast(null as varchar(70)) as shpng_tmptr_ctrl_ind,
    cast(null as varchar(70)) as scrap_itm_ind,
    cast(null as varchar(70)) as rebox_ww_ind,
    cast(null as varchar(70)) as rebox_nw_ind,
    cast(null as varchar(70)) as instrmnt_ind,
    cast(ismarkedfordeletion1 as varchar(1)) as ismarkedfordeletion1,
    
    -- ETL metadata
    current_timestamp as etl_load_dt,
    'INFORMATICA_MIGRATION' as etl_source_system

from {{ source('source_system', 'material_source') }}
where product is not null